
const SETUP_ROUTE = 'setup_route'
const APP_STAGE = 'APP_STAGE'
const SIGNIN_MODE = 'SIGNIN_MODE'

const REGISTER_FORM_SET_ERROR = 'REGISTER_FORM_SET_ERROR'
const SIGNIN_FORM_SET_ERROR = 'SIGNIN_FORM_SET_ERROR'

export { SETUP_ROUTE, APP_STAGE, SIGNIN_MODE, REGISTER_FORM_SET_ERROR, SIGNIN_FORM_SET_ERROR }