
const APPSTAGE_INITIAL = 'APPSTAGE_INITIAL'
const APPSTAGE_AUTH = 'APPSTAGE_AUTH'
const APPSTAGE_SIGNIN = 'APPSTAGE_SIGNIN'
const APPSTAGE_INITFAIL = 'APPSTAGE_INITFAIL'

const MODE_SIGNIN = 'MODE_SIGNIN'
const MODE_REGISTER = 'MODE_REGISTER'

export { 
	APPSTAGE_INITIAL, APPSTAGE_AUTH, APPSTAGE_SIGNIN, APPSTAGE_INITFAIL,
	MODE_SIGNIN, MODE_REGISTER
}